/* Bundled emoji dataset for the page icon picker.
   Generated from the Unicode Character Database (Python `unicodedata`) — names are the
   official Unicode names, lower-cased. BUNDLED ON PURPOSE: the picker must work under a
   strict CSP with no external host and no vendor sprite sheet, so the glyphs are plain
   text rendered by the system emoji font and the data is a static module.
   Single codepoints only (plus the two-codepoint regional-indicator flags) — every entry
   renders standalone, with no ZWJ-sequence fallback boxes.
   Regenerate: scripts/gen-emoji.py */

export interface EmojiGroup { key: string; label: string; emoji: [char: string, name: string][] }

export const EMOJI_GROUPS: EmojiGroup[] = [
  { key: "smileys", label: "Smileys", emoji: [
    ["😀","grinning face"],["😁","grinning face with smiling eyes"],["😂","face with tears of joy"],
    ["😃","smiling face with open mouth"],["😄","smiling face with open mouth and smiling eyes"],
    ["😅","smiling face with open mouth and cold sweat"],
    ["😆","smiling face with open mouth and tightly-closed eyes"],["😇","smiling face with halo"],
    ["😈","smiling face with horns"],["😉","winking face"],["😊","smiling face with smiling eyes"],
    ["😋","face savouring delicious food"],["😌","relieved face"],["😍","smiling face with heart-shaped eyes"],
    ["😎","smiling face with sunglasses"],["😏","smirking face"],["😐","neutral face"],["😑","expressionless face"],
    ["😒","unamused face"],["😓","face with cold sweat"],["😔","pensive face"],["😕","confused face"],
    ["😖","confounded face"],["😗","kissing face"],["😘","face throwing a kiss"],
    ["😙","kissing face with smiling eyes"],["😚","kissing face with closed eyes"],["😛","face with stuck-out tongue"],
    ["😜","face with stuck-out tongue and winking eye"],["😝","face with stuck-out tongue and tightly-closed eyes"],
    ["😞","disappointed face"],["😟","worried face"],["😠","angry face"],["😡","pouting face"],["😢","crying face"],
    ["😣","persevering face"],["😤","face with look of triumph"],["😥","disappointed but relieved face"],
    ["😦","frowning face with open mouth"],["😧","anguished face"],["😨","fearful face"],["😩","weary face"],
    ["😪","sleepy face"],["😫","tired face"],["😬","grimacing face"],["😭","loudly crying face"],
    ["😮","face with open mouth"],["😯","hushed face"],["😰","face with open mouth and cold sweat"],
    ["😱","face screaming in fear"],["😲","astonished face"],["😳","flushed face"],["😴","sleeping face"],
    ["😵","dizzy face"],["😶","face without mouth"],["😷","face with medical mask"],
    ["😸","grinning cat face with smiling eyes"],["😹","cat face with tears of joy"],
    ["😺","smiling cat face with open mouth"],["😻","smiling cat face with heart-shaped eyes"],
    ["😼","cat face with wry smile"],["😽","kissing cat face with closed eyes"],["😾","pouting cat face"],
    ["😿","crying cat face"],["🙀","weary cat face"],["🙁","slightly frowning face"],["🙂","slightly smiling face"],
    ["🙃","upside-down face"],["🙄","face with rolling eyes"],["🙅","face with no good gesture"],
    ["🙆","face with ok gesture"],["🙇","person bowing deeply"],["🙈","see-no-evil monkey"],
    ["🙉","hear-no-evil monkey"],["🙊","speak-no-evil monkey"],["🙋","happy person raising one hand"],
    ["🙌","person raising both hands in celebration"],["🙍","person frowning"],["🙎","person with pouting face"],
    ["🙏","person with folded hands"],["🤐","zipper-mouth face"],["🤑","money-mouth face"],
    ["🤒","face with thermometer"],["🤓","nerd face"],["🤔","thinking face"],["🤕","face with head-bandage"],
    ["🤖","robot face"],["🤗","hugging face"],["🤘","sign of the horns"],["🤙","call me hand"],
    ["🤚","raised back of hand"],["🤛","left-facing fist"],["🤜","right-facing fist"],["🤝","handshake"],
    ["🤞","hand with index and middle fingers crossed"],["🤟","i love you hand sign"],["🤠","face with cowboy hat"],
    ["🤡","clown face"],["🤢","nauseated face"],["🤣","rolling on the floor laughing"],["🤤","drooling face"],
    ["🤥","lying face"],["🤦","face palm"],["🤧","sneezing face"],["🤨","face with one eyebrow raised"],
    ["🤩","grinning face with star eyes"],["🤪","grinning face with one large and one small eye"],
    ["🤫","face with finger covering closed lips"],["🤬","serious face with symbols covering mouth"],
    ["🤭","smiling face with smiling eyes and hand covering mouth"],["🤮","face with open mouth vomiting"],
    ["🤯","shocked face with exploding head"],["🥰","smiling face with smiling eyes and three hearts"],
    ["🥱","yawning face"],["🥲","smiling face with tear"],["🥳","face with party horn and party hat"],
    ["🥴","face with uneven eyes and wavy mouth"],["🥵","overheated face"],["🥶","freezing face"],["🥷","ninja"],
    ["🥸","disguised face"],["🥺","face with pleading eyes"],
  ] },
  { key: "people", label: "People", emoji: [
    ["👤","bust in silhouette"],["👥","busts in silhouette"],["👦","boy"],["👧","girl"],["👨","man"],["👩","woman"],
    ["👪","family"],["👫","man and woman holding hands"],["👬","two men holding hands"],
    ["👭","two women holding hands"],["👮","police officer"],["👯","woman with bunny ears"],["👰","bride with veil"],
    ["👱","person with blond hair"],["👲","man with gua pi mao"],["👳","man with turban"],["👴","older man"],
    ["👵","older woman"],["👶","baby"],["👷","construction worker"],["👸","princess"],["👹","japanese ogre"],
    ["👺","japanese goblin"],["👻","ghost"],["👼","baby angel"],["👽","extraterrestrial alien"],["👾","alien monster"],
    ["👿","imp"],["💀","skull"],["💁","information desk person"],["💂","guardsman"],["💃","dancer"],["💄","lipstick"],
    ["💅","nail polish"],["💆","face massage"],["💇","haircut"],["🕴","man in business suit levitating"],
    ["🕵","sleuth or spy"],["🕶","dark sunglasses"],["🕷","spider"],["🕸","spider web"],["🕹","joystick"],
    ["🕺","man dancing"],["🕻","left hand telephone receiver"],["🕼","telephone receiver with page"],
    ["🕽","right hand telephone receiver"],["🕾","white touchtone telephone"],["🕿","black touchtone telephone"],
    ["🖀","telephone on top of modem"],["🖁","clamshell mobile phone"],["🖂","back of envelope"],
    ["🖃","stamped envelope"],["🖄","envelope with lightning"],["🖅","flying envelope"],
    ["🖆","pen over stamped envelope"],["🖇","linked paperclips"],["🖈","black pushpin"],["🖉","lower left pencil"],
    ["🖊","lower left ballpoint pen"],["🖋","lower left fountain pen"],["🖌","lower left paintbrush"],
    ["🖍","lower left crayon"],["🖎","left writing hand"],["🖏","turned ok hand sign"],
    ["🖐","raised hand with fingers splayed"],["🖑","reversed raised hand with fingers splayed"],
    ["🖒","reversed thumbs up sign"],["🖓","reversed thumbs down sign"],["🖔","reversed victory hand"],
    ["🖕","reversed hand with middle finger extended"],["🖖","raised hand with part between middle and ring fingers"],
    ["🧐","face with monocle"],["🧑","adult"],["🧒","child"],["🧓","older adult"],["🧔","bearded person"],
    ["🧕","person with headscarf"],["🧖","person in steamy room"],["🧗","person climbing"],
    ["🧘","person in lotus position"],["🧙","mage"],["🧚","fairy"],["🧛","vampire"],["🧜","merperson"],["🧝","elf"],
    ["🧞","genie"],["🧟","zombie"],["👊","fisted hand sign"],["👋","waving hand sign"],["👌","ok hand sign"],
    ["👍","thumbs up sign"],["👎","thumbs down sign"],["👏","clapping hands sign"],["👐","open hands sign"],
  ] },
  { key: "nature", label: "Nature", emoji: [
    ["🌀","cyclone"],["🌁","foggy"],["🌂","closed umbrella"],["🌃","night with stars"],["🌄","sunrise over mountains"],
    ["🌅","sunrise"],["🌆","cityscape at dusk"],["🌇","sunset over buildings"],["🌈","rainbow"],["🌉","bridge at night"],
    ["🌊","water wave"],["🌋","volcano"],["🌌","milky way"],["🌍","earth globe europe-africa"],
    ["🌎","earth globe americas"],["🌏","earth globe asia-australia"],["🌐","globe with meridians"],
    ["🌑","new moon symbol"],["🌒","waxing crescent moon symbol"],["🌓","first quarter moon symbol"],
    ["🌔","waxing gibbous moon symbol"],["🌕","full moon symbol"],["🌖","waning gibbous moon symbol"],
    ["🌗","last quarter moon symbol"],["🌘","waning crescent moon symbol"],["🌙","crescent moon"],
    ["🌚","new moon with face"],["🌛","first quarter moon with face"],["🌜","last quarter moon with face"],
    ["🌝","full moon with face"],["🌞","sun with face"],["🌟","glowing star"],["🌠","shooting star"],
    ["🌡","thermometer"],["🌢","black droplet"],["🌣","white sun"],["🌤","white sun with small cloud"],
    ["🌥","white sun behind cloud"],["🌦","white sun behind cloud with rain"],["🌧","cloud with rain"],
    ["🌨","cloud with snow"],["🌩","cloud with lightning"],["🌪","cloud with tornado"],["🌫","fog"],
    ["🌬","wind blowing face"],["🌰","chestnut"],["🌱","seedling"],["🌲","evergreen tree"],["🌳","deciduous tree"],
    ["🌴","palm tree"],["🌵","cactus"],["🌷","tulip"],["🌸","cherry blossom"],["🌹","rose"],["🌺","hibiscus"],
    ["🌻","sunflower"],["🌼","blossom"],["🌽","ear of maize"],["🌾","ear of rice"],["🌿","herb"],
    ["🍀","four leaf clover"],["🍁","maple leaf"],["🍂","fallen leaf"],["🍃","leaf fluttering in wind"],["🐀","rat"],
    ["🐁","mouse"],["🐂","ox"],["🐃","water buffalo"],["🐄","cow"],["🐅","tiger"],["🐆","leopard"],["🐇","rabbit"],
    ["🐈","cat"],["🐉","dragon"],["🐊","crocodile"],["🐋","whale"],["🐌","snail"],["🐍","snake"],["🐎","horse"],
    ["🐏","ram"],["🐐","goat"],["🐑","sheep"],["🐒","monkey"],["🐓","rooster"],["🐔","chicken"],["🐕","dog"],["🐖","pig"],
    ["🐗","boar"],["🐘","elephant"],["🐙","octopus"],["🐚","spiral shell"],["🐛","bug"],["🐜","ant"],["🐝","honeybee"],
    ["🐞","lady beetle"],["🐟","fish"],["🐠","tropical fish"],["🐡","blowfish"],["🐢","turtle"],["🐣","hatching chick"],
    ["🐤","baby chick"],["🐥","front-facing baby chick"],["🐦","bird"],["🐧","penguin"],["🐨","koala"],["🐩","poodle"],
    ["🐪","dromedary camel"],["🐫","bactrian camel"],["🐬","dolphin"],["🐭","mouse face"],["🐮","cow face"],
    ["🐯","tiger face"],["🐰","rabbit face"],["🐱","cat face"],["🐲","dragon face"],["🐳","spouting whale"],
    ["🐴","horse face"],["🐵","monkey face"],["🐶","dog face"],["🐷","pig face"],["🐸","frog face"],["🐹","hamster face"],
    ["🐺","wolf face"],["🐻","bear face"],["🐼","panda face"],["🐽","pig nose"],["🐾","paw prints"],["🐿","chipmunk"],
    ["🦀","crab"],["🦁","lion face"],["🦂","scorpion"],["🦃","turkey"],["🦄","unicorn face"],["🦅","eagle"],["🦆","duck"],
    ["🦇","bat"],["🦈","shark"],["🦉","owl"],["🦊","fox face"],["🦋","butterfly"],["🦌","deer"],["🦍","gorilla"],
    ["🦎","lizard"],["🦏","rhinoceros"],["🦐","shrimp"],["🦑","squid"],["🦒","giraffe face"],["🦓","zebra face"],
    ["🦔","hedgehog"],["🦕","sauropod"],["🦖","t-rex"],["🦗","cricket"],["🦘","kangaroo"],["🦙","llama"],["🦚","peacock"],
    ["🦛","hippopotamus"],["🦜","parrot"],["🦝","raccoon"],["🦞","lobster"],["🦟","mosquito"],["🦠","microbe"],
    ["🦡","badger"],["🦢","swan"],["🦣","mammoth"],["🦤","dodo"],["🦥","sloth"],["🦦","otter"],["🦧","orangutan"],
    ["🦨","skunk"],["🦩","flamingo"],["🦪","oyster"],["🦫","beaver"],["🦬","bison"],["🦭","seal"],["🦮","guide dog"],
    ["☀️","black sun with rays"],["☁️","cloud"],["☂️","umbrella"],["☃️","snowman"],["☄️","comet"],
    ["⛄️","snowman without snow"],["⛅️","sun behind cloud"],["⛆️","rain"],["⛇️","black snowman"],
    ["⛈️","thunder cloud and rain"],
  ] },
  { key: "food", label: "Food", emoji: [
    ["🌭","hot dog"],["🌮","taco"],["🌯","burrito"],["🍄","mushroom"],["🍅","tomato"],["🍆","aubergine"],["🍇","grapes"],
    ["🍈","melon"],["🍉","watermelon"],["🍊","tangerine"],["🍋","lemon"],["🍌","banana"],["🍍","pineapple"],
    ["🍎","red apple"],["🍏","green apple"],["🍐","pear"],["🍑","peach"],["🍒","cherries"],["🍓","strawberry"],
    ["🍔","hamburger"],["🍕","slice of pizza"],["🍖","meat on bone"],["🍗","poultry leg"],["🍘","rice cracker"],
    ["🍙","rice ball"],["🍚","cooked rice"],["🍛","curry and rice"],["🍜","steaming bowl"],["🍝","spaghetti"],
    ["🍞","bread"],["🍟","french fries"],["🍠","roasted sweet potato"],["🍡","dango"],["🍢","oden"],["🍣","sushi"],
    ["🍤","fried shrimp"],["🍥","fish cake with swirl design"],["🍦","soft ice cream"],["🍧","shaved ice"],
    ["🍨","ice cream"],["🍩","doughnut"],["🍪","cookie"],["🍫","chocolate bar"],["🍬","candy"],["🍭","lollipop"],
    ["🍮","custard"],["🍯","honey pot"],["🍰","shortcake"],["🍱","bento box"],["🍲","pot of food"],["🍳","cooking"],
    ["🍴","fork and knife"],["🍵","teacup without handle"],["🍶","sake bottle and cup"],["🍷","wine glass"],
    ["🍸","cocktail glass"],["🍹","tropical drink"],["🍺","beer mug"],["🍻","clinking beer mugs"],["🍼","baby bottle"],
    ["🍽","fork and knife with plate"],["🍾","bottle with popping cork"],["🍿","popcorn"],["🥐","croissant"],
    ["🥑","avocado"],["🥒","cucumber"],["🥓","bacon"],["🥔","potato"],["🥕","carrot"],["🥖","baguette bread"],
    ["🥗","green salad"],["🥘","shallow pan of food"],["🥙","stuffed flatbread"],["🥚","egg"],["🥛","glass of milk"],
    ["🥜","peanuts"],["🥝","kiwifruit"],["🥞","pancakes"],["🥟","dumpling"],["🥠","fortune cookie"],["🥡","takeout box"],
    ["🥢","chopsticks"],["🥣","bowl with spoon"],["🥤","cup with straw"],["🥥","coconut"],["🥦","broccoli"],["🥧","pie"],
    ["🥨","pretzel"],["🥩","cut of meat"],["🥪","sandwich"],["🥫","canned food"],["🥬","leafy green"],["🥭","mango"],
    ["🥮","moon cake"],["🥯","bagel"],["🧀","cheese wedge"],["🧁","cupcake"],["🧂","salt shaker"],["🧃","beverage box"],
    ["🧄","garlic"],["🧅","onion"],["🧆","falafel"],["🧇","waffle"],["🧈","butter"],["🧉","mate drink"],["🧊","ice cube"],
    ["🧋","bubble tea"],
  ] },
  { key: "activity", label: "Activity", emoji: [
    ["🎀","ribbon"],["🎁","wrapped present"],["🎂","birthday cake"],["🎃","jack-o-lantern"],["🎄","christmas tree"],
    ["🎅","father christmas"],["🎆","fireworks"],["🎇","firework sparkler"],["🎈","balloon"],["🎉","party popper"],
    ["🎊","confetti ball"],["🎋","tanabata tree"],["🎌","crossed flags"],["🎍","pine decoration"],
    ["🎎","japanese dolls"],["🎏","carp streamer"],["🎐","wind chime"],["🎑","moon viewing ceremony"],
    ["🎒","school satchel"],["🎓","graduation cap"],["🎔","heart with tip on the left"],["🎕","bouquet of flowers"],
    ["🎖","military medal"],["🎗","reminder ribbon"],["🎘","musical keyboard with jacks"],["🎙","studio microphone"],
    ["🎚","level slider"],["🎛","control knobs"],["🎜","beamed ascending musical notes"],
    ["🎝","beamed descending musical notes"],["🎞","film frames"],["🎟","admission tickets"],["🎠","carousel horse"],
    ["🎡","ferris wheel"],["🎢","roller coaster"],["🎣","fishing pole and fish"],["🎤","microphone"],
    ["🎥","movie camera"],["🎦","cinema"],["🎧","headphone"],["🎨","artist palette"],["🎩","top hat"],
    ["🎪","circus tent"],["🎫","ticket"],["🎬","clapper board"],["🎭","performing arts"],["🎮","video game"],
    ["🎯","direct hit"],["🎰","slot machine"],["🎱","billiards"],["🎲","game die"],["🎳","bowling"],
    ["🎴","flower playing cards"],["🎵","musical note"],["🎶","multiple musical notes"],["🎷","saxophone"],
    ["🎸","guitar"],["🎹","musical keyboard"],["🎺","trumpet"],["🎻","violin"],["🎼","musical score"],
    ["🎽","running shirt with sash"],["🎾","tennis racquet and ball"],["🎿","ski and ski boot"],
    ["🏀","basketball and hoop"],["🏁","chequered flag"],["🏂","snowboarder"],["🏃","runner"],["🏄","surfer"],
    ["🏅","sports medal"],["🏆","trophy"],["🏇","horse racing"],["🏈","american football"],["🏉","rugby football"],
    ["🏊","swimmer"],["🏋","weight lifter"],["🏌","golfer"],["🏍","racing motorcycle"],["🏎","racing car"],
    ["🏏","cricket bat and ball"],["🏸","badminton racquet and shuttlecock"],["🏹","bow and arrow"],["🏺","amphora"],
    ["⚽️","soccer ball"],["⚾️","baseball"],["⛰️","mountain"],["⛱️","umbrella on ground"],["⛲️","fountain"],
    ["⛳️","flag in hole"],["⛴️","ferry"],["⛵️","sailboat"],["⛶️","square four corners"],["⛷️","skier"],
    ["⛸️","ice skate"],["⛹️","person with ball"],["🥇","first place medal"],["🥈","second place medal"],
    ["🥉","third place medal"],["🥊","boxing glove"],["🥋","martial arts uniform"],["🥌","curling stone"],
    ["🥍","lacrosse stick and ball"],["🥎","softball"],["🥏","flying disc"],
  ] },
  { key: "travel", label: "Travel", emoji: [
    ["🚀","rocket"],["🚁","helicopter"],["🚂","steam locomotive"],["🚃","railway car"],["🚄","high-speed train"],
    ["🚅","high-speed train with bullet nose"],["🚆","train"],["🚇","metro"],["🚈","light rail"],["🚉","station"],
    ["🚊","tram"],["🚋","tram car"],["🚌","bus"],["🚍","oncoming bus"],["🚎","trolleybus"],["🚏","bus stop"],
    ["🚐","minibus"],["🚑","ambulance"],["🚒","fire engine"],["🚓","police car"],["🚔","oncoming police car"],
    ["🚕","taxi"],["🚖","oncoming taxi"],["🚗","automobile"],["🚘","oncoming automobile"],["🚙","recreational vehicle"],
    ["🚚","delivery truck"],["🚛","articulated lorry"],["🚜","tractor"],["🚝","monorail"],["🚞","mountain railway"],
    ["🚟","suspension railway"],["🚠","mountain cableway"],["🚡","aerial tramway"],["🚢","ship"],["🚣","rowboat"],
    ["🚤","speedboat"],["🚥","horizontal traffic light"],["🚦","vertical traffic light"],["🚧","construction sign"],
    ["🚨","police cars revolving light"],["🚩","triangular flag on post"],["🚪","door"],["🚫","no entry sign"],
    ["🚬","smoking symbol"],["🚭","no smoking symbol"],["🚮","put litter in its place symbol"],
    ["🚯","do not litter symbol"],["🚰","potable water symbol"],["🚱","non-potable water symbol"],["🚲","bicycle"],
    ["🚳","no bicycles"],["🚴","bicyclist"],["🚵","mountain bicyclist"],["🚶","pedestrian"],["🚷","no pedestrians"],
    ["🚸","children crossing"],["🚹","mens symbol"],["🚺","womens symbol"],["🚻","restroom"],["🚼","baby symbol"],
    ["🚽","toilet"],["🚾","water closet"],["🚿","shower"],["🛀","bath"],["🛁","bathtub"],["🛂","passport control"],
    ["🛃","customs"],["🛄","baggage claim"],["🛅","left luggage"],["🛆","triangle with rounded corners"],
    ["🛇","prohibited sign"],["🛈","circled information source"],["🛉","boys symbol"],["🛊","girls symbol"],
    ["🛋","couch and lamp"],["🛌","sleeping accommodation"],["🛍","shopping bags"],["🛎","bellhop bell"],["🛏","bed"],
    ["🛐","place of worship"],["🛑","octagonal sign"],["🛒","shopping trolley"],["🛓","stupa"],["🛔","pagoda"],
    ["🛕","hindu temple"],["🛖","hut"],["🛗","elevator"],["🛠","hammer and wrench"],["🛡","shield"],["🛢","oil drum"],
    ["🛣","motorway"],["🛤","railway track"],["🛥","motor boat"],["🛦","up-pointing military airplane"],
    ["🛧","up-pointing airplane"],["🛨","up-pointing small airplane"],["🛩","small airplane"],
    ["🛪","northeast-pointing airplane"],["🛫","airplane departure"],["🛬","airplane arriving"],["🛰","satellite"],
    ["🛱","oncoming fire engine"],["🛲","diesel locomotive"],["🛳","passenger ship"],["🛴","scooter"],
    ["🛵","motor scooter"],["🛶","canoe"],["🛷","sled"],["🛸","flying saucer"],["🛹","skateboard"],["🛺","auto rickshaw"],
    ["🛻","pickup truck"],["🛼","roller skate"],["🏠","house building"],["🏡","house with garden"],
    ["🏢","office building"],["🏣","japanese post office"],["🏤","european post office"],["🏥","hospital"],["🏦","bank"],
    ["🏧","automated teller machine"],["🏨","hotel"],["🏩","love hotel"],["🏪","convenience store"],["🏫","school"],
    ["🏬","department store"],["🏭","factory"],["🏮","izakaya lantern"],["🏯","japanese castle"],
    ["🏰","european castle"],["🗺","world map"],["🗻","mount fuji"],["🗼","tokyo tower"],["🗽","statue of liberty"],
    ["🗾","silhouette of japan"],["🗿","moyai"],["✈️","airplane"],
  ] },
  { key: "objects", label: "Objects", emoji: [
    ["💠","diamond shape with a dot inside"],["💡","electric light bulb"],["💢","anger symbol"],["💣","bomb"],
    ["💤","sleeping symbol"],["💥","collision symbol"],["💦","splashing sweat symbol"],["💧","droplet"],
    ["💨","dash symbol"],["💩","pile of poo"],["💪","flexed biceps"],["💫","dizzy symbol"],["💬","speech balloon"],
    ["💭","thought balloon"],["💮","white flower"],["💯","hundred points symbol"],["💰","money bag"],
    ["💱","currency exchange"],["💲","heavy dollar sign"],["💳","credit card"],["💴","banknote with yen sign"],
    ["💵","banknote with dollar sign"],["💶","banknote with euro sign"],["💷","banknote with pound sign"],
    ["💸","money with wings"],["💹","chart with upwards trend and yen sign"],["💺","seat"],["💻","personal computer"],
    ["💼","briefcase"],["💽","minidisc"],["💾","floppy disk"],["💿","optical disc"],["📀","dvd"],["📁","file folder"],
    ["📂","open file folder"],["📃","page with curl"],["📄","page facing up"],["📅","calendar"],
    ["📆","tear-off calendar"],["📇","card index"],["📈","chart with upwards trend"],
    ["📉","chart with downwards trend"],["📊","bar chart"],["📋","clipboard"],["📌","pushpin"],["📍","round pushpin"],
    ["📎","paperclip"],["📏","straight ruler"],["📐","triangular ruler"],["📑","bookmark tabs"],["📒","ledger"],
    ["📓","notebook"],["📔","notebook with decorative cover"],["📕","closed book"],["📖","open book"],
    ["📗","green book"],["📘","blue book"],["📙","orange book"],["📚","books"],["📛","name badge"],["📜","scroll"],
    ["📝","memo"],["📞","telephone receiver"],["📟","pager"],["📠","fax machine"],["📡","satellite antenna"],
    ["📢","public address loudspeaker"],["📣","cheering megaphone"],["📤","outbox tray"],["📥","inbox tray"],
    ["📦","package"],["📧","e-mail symbol"],["📨","incoming envelope"],["📩","envelope with downwards arrow above"],
    ["📪","closed mailbox with lowered flag"],["📫","closed mailbox with raised flag"],
    ["📬","open mailbox with raised flag"],["📭","open mailbox with lowered flag"],["📮","postbox"],
    ["📯","postal horn"],["📰","newspaper"],["📱","mobile phone"],["📲","mobile phone with rightwards arrow at left"],
    ["📳","vibration mode"],["📴","mobile phone off"],["📵","no mobile phones"],["📶","antenna with bars"],
    ["📷","camera"],["📸","camera with flash"],["📹","video camera"],["📺","television"],["📻","radio"],
    ["📼","videocassette"],["📽","film projector"],["📾","portable stereo"],["📿","prayer beads"],
    ["🔦","electric torch"],["🔧","wrench"],["🔨","hammer"],["🔩","nut and bolt"],["🔪","hocho"],["🔫","pistol"],
    ["🔬","microscope"],["🔭","telescope"],["🔮","crystal ball"],["🔯","six pointed star with middle dot"],
    ["🔰","japanese symbol for beginner"],["🔱","trident emblem"],["🔲","black square button"],
    ["🔳","white square button"],["🔴","large red circle"],["🔵","large blue circle"],["🔶","large orange diamond"],
    ["🔷","large blue diamond"],["🔸","small orange diamond"],["🔹","small blue diamond"],
    ["🔺","up-pointing red triangle"],["🔻","down-pointing red triangle"],["🔼","up-pointing small red triangle"],
    ["🔽","down-pointing small red triangle"],["🧰","toolbox"],["🧱","brick"],["🧲","magnet"],["🧳","luggage"],
    ["🧴","lotion bottle"],["🧵","spool of thread"],["🧶","ball of yarn"],["🧷","safety pin"],["🧸","teddy bear"],
    ["🧹","broom"],["🧺","basket"],["🧻","roll of paper"],["🧼","bar of soap"],["🧽","sponge"],["🧾","receipt"],
    ["🧿","nazar amulet"],["✂️","black scissors"],["✃️","lower blade scissors"],["✄️","white scissors"],
    ["✅️","white heavy check mark"],["✆️","telephone location sign"],["✇️","tape drive"],["✉️","envelope"],
    ["✊️","raised fist"],["✋️","raised hand"],["✌️","victory hand"],["✍️","writing hand"],
    ["✎️","lower right pencil"],["✏️","pencil"],["✐️","upper right pencil"],["✑️","white nib"],["✒️","black nib"],
  ] },
  { key: "symbols", label: "Symbols", emoji: [
    ["🔀","twisted rightwards arrows"],["🔁","clockwise rightwards and leftwards open circle arrows"],
    ["🔂","clockwise rightwards and leftwards open circle arrows with circled one overlay"],
    ["🔃","clockwise downwards and upwards open circle arrows"],
    ["🔄","anticlockwise downwards and upwards open circle arrows"],["🔅","low brightness symbol"],
    ["🔆","high brightness symbol"],["🔇","speaker with cancellation stroke"],["🔈","speaker"],
    ["🔉","speaker with one sound wave"],["🔊","speaker with three sound waves"],["🔋","battery"],
    ["🔌","electric plug"],["🔍","left-pointing magnifying glass"],["🔎","right-pointing magnifying glass"],
    ["🔏","lock with ink pen"],["🔐","closed lock with key"],["🔑","key"],["🔒","lock"],["🔓","open lock"],["🔔","bell"],
    ["🔕","bell with cancellation stroke"],["🔖","bookmark"],["🔗","link symbol"],["🔘","radio button"],
    ["🔙","back with leftwards arrow above"],["🔚","end with leftwards arrow above"],
    ["🔛","on with exclamation mark with left right arrow above"],["🔜","soon with rightwards arrow above"],
    ["🔝","top with upwards arrow above"],["🔞","no one under eighteen symbol"],["🔟","keycap ten"],
    ["🔠","input symbol for latin capital letters"],["🔡","input symbol for latin small letters"],
    ["🔢","input symbol for numbers"],["🔣","input symbol for symbols"],["🔤","input symbol for latin letters"],
    ["🔥","fire"],["🆑","squared cl"],["🆒","squared cool"],["🆓","squared free"],["🆔","squared id"],
    ["🆕","squared new"],["🆖","squared ng"],["🆗","squared ok"],["🆘","squared sos"],
    ["🆙","squared up with exclamation mark"],["🆚","squared vs"],["🔾","lower right shadowed white circle"],
    ["🔿","upper right shadowed white circle"],["🕀","circled cross pommee"],
    ["🕁","cross pommee with half-circle below"],["🕂","cross pommee"],
    ["🕃","notched left semicircle with three dots"],["🕄","notched right semicircle with three dots"],
    ["🕅","symbol for marks chapter"],["🕆","white latin cross"],["🕇","heavy latin cross"],["🕈","celtic cross"],
    ["🕉","om symbol"],["🕊","dove of peace"],["🕋","kaaba"],["🕌","mosque"],["🕍","synagogue"],
    ["🕎","menorah with nine branches"],["🕏","bowl of hygieia"],["🕐","clock face one oclock"],
    ["🕑","clock face two oclock"],["🕒","clock face three oclock"],["🕓","clock face four oclock"],
    ["🕔","clock face five oclock"],["🕕","clock face six oclock"],["🕖","clock face seven oclock"],
    ["🕗","clock face eight oclock"],["🕘","clock face nine oclock"],["🕙","clock face ten oclock"],
    ["🕚","clock face eleven oclock"],["🕛","clock face twelve oclock"],["🕜","clock face one-thirty"],
    ["🕝","clock face two-thirty"],["🕞","clock face three-thirty"],["🕟","clock face four-thirty"],
    ["🕠","clock face five-thirty"],["🕡","clock face six-thirty"],["🕢","clock face seven-thirty"],
    ["🕣","clock face eight-thirty"],["🕤","clock face nine-thirty"],["🕥","clock face ten-thirty"],
    ["🕦","clock face eleven-thirty"],["🕧","clock face twelve-thirty"],["✨️","sparkles"],["❌️","cross mark"],
    ["❍️","shadowed white circle"],["❎️","negative squared cross mark"],["❓️","black question mark ornament"],
    ["❔️","white question mark ornament"],["❕️","white exclamation mark ornament"],
    ["❖️","black diamond minus white x"],["❗️","heavy exclamation mark symbol"],["➕️","heavy plus sign"],
    ["➖️","heavy minus sign"],["➗️","heavy division sign"],["➡️","black rightwards arrow"],
    ["➢️","three-d top-lighted rightwards arrowhead"],["➣️","three-d bottom-lighted rightwards arrowhead"],
    ["➤️","black rightwards arrowhead"],["➥️","heavy black curved downwards and rightwards arrow"],
    ["➦️","heavy black curved upwards and rightwards arrow"],["➧️","squat black rightwards arrow"],
    ["➨️","heavy concave-pointed black rightwards arrow"],["➩️","right-shaded white rightwards arrow"],
    ["➪️","left-shaded white rightwards arrow"],["➫️","back-tilted shadowed white rightwards arrow"],
    ["➬️","front-tilted shadowed white rightwards arrow"],
    ["➭️","heavy lower right-shadowed white rightwards arrow"],
    ["➮️","heavy upper right-shadowed white rightwards arrow"],
    ["➯️","notched lower right-shadowed white rightwards arrow"],["➰️","curly loop"],["⬅️","leftwards black arrow"],
    ["⬆️","upwards black arrow"],["⬇️","downwards black arrow"],["⬛️","black large square"],
    ["⬜️","white large square"],["⭐️","white medium star"],["⭑️","black small star"],["⭒️","white small star"],
    ["⭓️","black right-pointing pentagon"],["⭔️","white right-pointing pentagon"],["⭕️","heavy large circle"],
  ] },
  { key: "flags", label: "Flags", emoji: [
    ["🇫🇷","france flag"],["🇬🇧","united kingdom flag"],["🇺🇸","united states flag"],["🇩🇪","germany flag"],
    ["🇪🇸","spain flag"],["🇮🇹","italy flag"],["🇧🇪","belgium flag"],["🇳🇱","netherlands flag"],["🇵🇹","portugal flag"],
    ["🇨🇭","switzerland flag"],["🇦🇹","austria flag"],["🇸🇪","sweden flag"],["🇳🇴","norway flag"],["🇩🇰","denmark flag"],
    ["🇫🇮","finland flag"],["🇮🇪","ireland flag"],["🇵🇱","poland flag"],["🇨🇿","czechia flag"],["🇬🇷","greece flag"],
    ["🇹🇷","turkey flag"],["🇷🇺","russia flag"],["🇺🇦","ukraine flag"],["🇨🇦","canada flag"],["🇲🇽","mexico flag"],
    ["🇧🇷","brazil flag"],["🇦🇷","argentina flag"],["🇨🇳","china flag"],["🇯🇵","japan flag"],["🇰🇷","south korea flag"],
    ["🇮🇳","india flag"],["🇦🇺","australia flag"],["🇳🇿","new zealand flag"],["🇿🇦","south africa flag"],
    ["🇳🇬","nigeria flag"],["🇪🇬","egypt flag"],["🇲🇦","morocco flag"],["🇦🇪","united arab emirates flag"],
    ["🇸🇦","saudi arabia flag"],["🇮🇱","israel flag"],["🇸🇬","singapore flag"],["🇹🇭","thailand flag"],
    ["🇻🇳","vietnam flag"],["🇮🇩","indonesia flag"],
  ] },
];


/* flat index for search — built once at module load */
export const EMOJI_ALL: [char: string, name: string, group: string][] =
  EMOJI_GROUPS.flatMap((g) => g.emoji.map(([c, n]) => [c, n, g.key] as [string, string, string]));

export function searchEmoji(q: string, limit = 96): [char: string, name: string, group: string][] {
  const t = q.trim().toLowerCase();
  if (!t) return [];
  const starts: typeof EMOJI_ALL = [], has: typeof EMOJI_ALL = [];
  for (const e of EMOJI_ALL) {
    if (e[1].startsWith(t)) starts.push(e);
    else if (e[1].includes(t)) has.push(e);
    if (starts.length >= limit) break;
  }
  return [...starts, ...has].slice(0, limit);
}
